version: '3.4'

services:

  interpreter:
    container_name: python-toprtg
    build:
      context: ./
      dockerfile: ./python/python.Dockerfile
    volumes:
      - ./python/entrypoint.sh:/entrypoint.sh
    entrypoint: /entrypoint.sh

  db:
    container_name: mysql-toprtg
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: '${DB_NAME}'
      MYSQL_USER: '${DB_USER}'
      MYSQL_PASSWORD: '${DB_PASS}'
      MYSQL_ROOT_PASSWORD: '${DB_PASS}'
    ports:
      - '${DB_PORT}:3306'
    volumes:
      - toprtg-db:/var/lib/mysql

  web:
    container_name: phpmyadmin-toprtg
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '${PHPMYADMIN_PORT}:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${DB_PASS}

volumes:
  toprtg-db:

networks:
  web-db-net: